FROM python:3.12-slim

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    python3-dev \
    python3-pip \
    libjpeg-dev \
    zlib1g-dev \
    libfreetype6-dev \
    libharfbuzz-dev \
    libleptonica-dev \
    libtesseract-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*


COPY requirements.txt ./

RUN python -m pip install --no-cache-dir -r requirements.txt --only-binary pymupdf

COPY ./*.py .

CMD ["python","./main.py"]