networks:
  database:
    driver: bridge

services:
  challenge:
    build:
      context: ./challenge
      dockerfile: Dockerfile
    container_name: challenge
    ports:
      - "5000:5000"
    env_file:
      - .env

  checkpoint:
    build:
      context: ./checkpoint
      dockerfile: Dockerfile
    container_name: checkpoint
    ports:
      - "5001:5000"
    env_file:
      - .env

  course:
    build:
      context: ./course
      dockerfile: Dockerfile
    container_name: course
    ports:
      - "5002:5000"
    env_file:
      - .env

  friends:
    build:
      context: ./friends
      dockerfile: Dockerfile
    container_name: friends
    ports:
      - "5003:5000"
    env_file:
      - .env

  module:
    build:
      context: ./module
      dockerfile: Dockerfile
    container_name: module
    ports:
      - "5004:5000"
    env_file:
      - .env

  notes:
    build:
      context: ./notes
      dockerfile: Dockerfile
    container_name: notes
    ports:
      - "5005:5000"
    env_file:
      - .env

  questions:
    build:
      context: ./questions
      dockerfile: Dockerfile
    container_name: questions
    ports:
      - "5006:5000"
    env_file:
      - .env

  storage:
    build:
      context: ./storage
      dockerfile: Dockerfile
    container_name: storage
    ports:
      - "5007:5000"
    env_file:
      - .env

  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    container_name: users
    ports:
      - "5008:5000"
    env_file:
      - .env
